from uuid import UUID

from schemas import DTO, ExistsGetResponse, FollowListResponse


class FollowServiceModel:
    async def exists(self, follower_id: UUID, followed_id: UUID) -> ExistsGetResponse: ...
    async def create_follow(self, follower_id: UUID, followed_id: UUID) -> DTO: ...
    async def remove_follow(self, follower_id: UUID, followed_id: UUID) -> DTO: ...
    async def get_user_follows(self, user_id: UUID) -> FollowListResponse: ...