from typing import BinaryIO
from uuid import UUID, uuid4

class ImageUploadServiceModel:
    async def init(self) -> None: ...
    async def test_connection(self) -> None: ...
    async def create_image(self, stream: BinaryIO, filename: str = str(uuid4())) -> tuple[str, str]: ...
    async def destroy_image(self, public_id: UUID): ...