from uuid import UUID

from starlette.datastructures import UploadFile
from fastapi import UploadFile as FastAPIUploadFile


class ImageServiceModel:
    async def init(self) -> None: ...
    async def test_connection(self) -> None: ...
    async def create_image(self, image: UploadFile | FastAPIUploadFile) -> tuple[str, str]: ...
    async def destroy_image(self, public_id: UUID): ...