from uuid import UUID

from schemas import DTO, UserGetResponse


class UserServiceModel:
    async def get_user(self, id: UUID) -> UserGetResponse: ...
    async def register(self, username: str, password: str, name: str | None) -> UserGetResponse: ...
    async def log_in(self, username: str, password: str) -> UserGetResponse: ...
    async def set_name(self, id: UUID, name: str) -> DTO: ...
    async def change_username(self, id: UUID, username: str) -> DTO: ...
    async def change_password(self, id: UUID, old_password: str, new_password: str) -> DTO: ...